/**
 * AUTO-GENERATED FILE — DO NOT EDIT
 *
 * Generated by scripts/svg-to-tsx.mjs from SVG files in this directory.
 * This file is regenerated during build and should not be committed to git.
 */
import type { FC, SVGProps } from 'react';

export type IconComponent = FC<SVGProps<SVGSVGElement>>;

const AddWithIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg width={22} height={20} viewBox="0 0 22 20" {...props}>
    <path
      fill="#7A8291"
      fillRule="evenodd"
      d="M16.5 16 13 12h7zm-4-5.75H9.75a.5.5 0 0 0-.5.5v2.75a.5.5 0 0 1-.5.5h-1.5a.5.5 0 0 1-.5-.5v-2.75a.5.5 0 0 0-.5-.5H3.5a.5.5 0 0 1-.5-.5v-1.5a.5.5 0 0 1 .5-.5h2.75a.5.5 0 0 0 .5-.5V4.5a.5.5 0 0 1 .5-.5h1.5a.5.5 0 0 1 .5.5v2.75a.5.5 0 0 0 .5.5h2.75a.5.5 0 0 1 .5.5v1.5a.5.5 0 0 1-.5.5"
    />
  </svg>
);

const AddIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" {...props}>
    <path d="M19 14h-4a1 1 0 0 0-1 1v4a1 1 0 0 1-1 1h-2a1 1 0 0 1-1-1v-4a1 1 0 0 0-1-1H5a1 1 0 0 1-1-1v-2a1 1 0 0 1 1-1h4a1 1 0 0 0 1-1V5a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v4a1 1 0 0 0 1 1h4a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1" />
  </svg>
);

const ArrowIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg viewBox="0 0 24 24" {...props}>
    <path
      fill="#313D3E"
      d="m10.506 19.916 1.903-1.953-4.744-4.67H21.31V10.55H7.665l4.744-4.682-1.903-1.953-7.95 8z"
    />
  </svg>
);

const AzureIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg width={26} height={26} viewBox="0 0 26 26" {...props}>
    <path
      fill="#2684FF"
      d="M14.015 4.217 7.1 9.927 1.5 19.751l5.27.055zm.77 1.263-3.02 8.014 5.6 6.313-10.76 1.92 17.895.056Z"
    />
  </svg>
);

const BitbucketIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg width={26} height={26} viewBox="0 0 26 26" {...props}>
    <path
      fill="#2684FF"
      d="M2.776 3a.655.655 0 0 0-.655.76l2.781 16.886c.072.427.44.74.872.744h13.344a.655.655 0 0 0 .655-.55l2.782-17.077a.655.655 0 0 0-.655-.76zm11.713 12.204h-4.26L9.076 9.18h6.445z"
    />
  </svg>
);

const BoldIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg width={22} height={20} viewBox="0 0 22 20" {...props}>
    <path
      fill="#7A8291"
      d="M13.2 9.819c.812-.577 1.381-1.525 1.381-2.404 0-1.948-1.465-3.448-3.348-3.448H6v12.066h5.894c1.75 0 3.106-1.465 3.106-3.267 0-1.31-.72-2.43-1.8-2.947M8.108 6.122h2.85c.788 0 1.424.577 1.424 1.293 0 .715-.636 1.292-1.425 1.292h-2.85zm3.324 7.756H8.108v-2.585h3.324c.789 0 1.425.577 1.425 1.292s-.636 1.293-1.425 1.293"
    />
  </svg>
);

const CheckIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg viewBox="-1 -2 16 16" {...props}>
    <path d="m4.016 11-.648-.946a6 6 0 0 0-.157-.22l-.096-.133-.511-.7a7 7 0 0 0-.162-.214l-.102-.134-.265-.346a27 27 0 0 0-.543-.687l-.11-.136a22 22 0 0 0-.442-.54l-.278-.332a9 9 0 0 0-.192-.225L.417 6.28l-.283-.324L0 5.805l1.376-1.602c.04.027.186.132.186.132l.377.272.129.095q.12.086.237.175l.37.28c.192.142.382.292.565.436l.162.126c.27.21.503.398.714.574l.477.393q.118.095.23.194l.433.375.171-.205A51 51 0 0 1 8.18 4.023a35 35 0 0 1 2.382-2.213q.312-.263.635-.518l.328-.255.333-.245q.108-.082.221-.159l.117-.083q.166-.117.341-.23c.163-.11.334-.217.503-.32l1.158 1.74a12 12 0 0 0-.64.55l-.065.06q-.105.092-.207.192l-.258.249-.26.265a22 22 0 0 0-.512.539 33 33 0 0 0-1.915 2.313 52 52 0 0 0-2.572 3.746l-.392.642-.19.322-.233.382z" />
  </svg>
);

const ChevronDoubleIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg viewBox="0 0 24 24" {...props}>
    <path d="m5.123 3.33-2.26 2.137 8.656 9.15 9.344-9.105-2.17-2.228-7.084 6.902z" />
    <path d="m5.123 10.33-2.26 2.137 8.656 9.15 9.344-9.105-2.17-2.228-7.084 6.902z" />
  </svg>
);

const ChevronIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg viewBox="0 0 24 24" {...props}>
    <path d="m5.123 6.33-2.26 2.137 8.656 9.15 9.344-9.105-2.17-2.228-7.084 6.902z" />
  </svg>
);

const CircleIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" {...props}>
    <circle cx={12} cy={12} r={4} />
  </svg>
);

const CloseIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg viewBox="0 0 24 24" {...props}>
    <path d="M11.916 9.96 6.282 4.345 4.398 6.401l5.634 5.616-5.616 5.617 1.849 2.022 5.616-5.617 5.616 5.6 1.884-2.04L13.765 12l5.633-5.634-1.866-2.022z" />
  </svg>
);

const CodeBlockIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg width={22} height={20} viewBox="0 0 22 20" {...props}>
    <path
      fill="#7A8291"
      d="M10.103 13.32 7.05 10l3.052-3.32-1.325-1.01L4.798 10l3.98 4.33zM5 4h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2m6.927 9.32 1.217.935 3.98-4.33-3.98-4.33-1.217 1.085L14.978 10z"
    />
  </svg>
);

const CodeIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg width={22} height={20} viewBox="0 0 22 20" {...props}>
    <path
      fill="#7A8291"
      d="M9 14.6 4.649 10 9 5.4 7.676 4 2 10l5.676 6zm3 0 4.351-4.6L12 5.4 13.324 4 19 10l-5.676 6z"
    />
  </svg>
);

const DecapIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg width={335} height={90} fill="none" viewBox="0 0 335 90" {...props}>
    <path
      fill="#FF0082"
      d="M30.73.15 0 2.95l3.67 40.21 20.03-1.83-1.99-21.86 10.71-.98c10.61-.97 19.14 7.53 20.29 20.19l19.67-1.79C70.34 14.72 51.64-1.75 30.73.15M73.61 49.51c0 12.72-7.73 21.95-18.37 21.95H44.49V49.47H24.38v40.42h30.86c21.02 0 38.12-18.11 38.12-40.38v-.04H73.61z"
      className="no-fill"
    />
    <path
      fill="#000"
      d="M131.65 23.71h20.01c14.41 0 24.29 9.09 24.29 23.06s-9.88 23.06-24.29 23.06h-20.01zm19.51 37.35c8.75 0 14.47-5.47 14.47-14.29s-5.73-14.29-14.47-14.29h-9.31v28.59h9.31zM207.61 58.69l5.22 5.93c-3.15 3.75-7.87 5.73-13.97 5.73-11.7 0-19.32-7.71-19.32-18.25s7.68-18.25 18.12-18.25c9.56 0 17.43 6.59 17.49 17.92l-25.04 5.07c1.45 3.49 4.59 5.27 9 5.27 3.59 0 6.17-1.12 8.5-3.43zm-18.44-7.64 16.49-3.36c-.94-3.62-3.9-6.06-7.99-6.06-4.91 0-8.31 3.43-8.5 9.42M218.25 52.1c0-10.67 7.87-18.25 18.88-18.25 7.11 0 12.71 3.23 15.17 9.02l-7.61 4.28c-1.83-3.36-4.53-4.87-7.61-4.87-4.97 0-8.87 3.62-8.87 9.81s3.9 9.81 8.87 9.81c3.08 0 5.79-1.45 7.61-4.87l7.61 4.35c-2.45 5.67-8.05 8.96-15.17 8.96-11.01 0-18.88-7.58-18.88-18.25zM290.93 34.38v35.44h-9.38v-4.08c-2.45 3.1-6.04 4.61-10.57 4.61-9.57 0-16.93-7.11-16.93-18.25s7.36-18.25 16.93-18.25c4.15 0 7.68 1.38 10.13 4.28v-3.75zM281.3 52.1c0-6.13-3.78-9.81-8.62-9.81S264 45.98 264 52.1s3.78 9.81 8.68 9.81 8.62-3.69 8.62-9.81M334.54 52.1c0 11.13-7.36 18.25-16.86 18.25-4.22 0-7.68-1.38-10.19-4.28V82.6h-9.82V34.38h9.38v4.08c2.45-3.1 6.1-4.61 10.63-4.61 9.5 0 16.86 7.11 16.86 18.25m-9.94 0c0-6.13-3.71-9.81-8.62-9.81s-8.62 3.69-8.62 9.81 3.71 9.81 8.62 9.81 8.62-3.69 8.62-9.81"
    />
  </svg>
);

const DragHandleIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg viewBox="0 0 24 24" {...props}>
    <path d="M3 15v-2h18v2zm0-4V9h18v2z" />
  </svg>
);

const EyeIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg viewBox="0 0 24 24" {...props}>
    <path d="M22.557 11.492C21.13 10 16.849 6 12.395 6c-4.8 0-8.844 4-10.184 5.492a.8.8 0 0 0 0 1.081C3.55 14.043 7.616 18 12.395 18c4.756 0 8.8-3.914 10.162-5.405a.783.783 0 0 0 0-1.103m-10.14 4.692a4.152 4.152 0 0 1 0-8.303 4.15 4.15 0 0 1 4.15 4.151c0 2.292-1.88 4.152-4.15 4.152m0-2.79a1.362 1.362 0 1 0 0-2.724 1.362 1.362 0 0 0 0 2.725" />
  </svg>
);

const FolderIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" {...props}>
    <path d="M10 5H5a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2h-7z" />
  </svg>
);

const GiteaIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg
    width={16}
    height={16}
    aria-hidden="true"
    className="svg gitea-gitea"
    viewBox="0 0 640 640"
    {...props}
  >
    <g fill="#609926">
      <path d="M622.7 149.8c-4.1-4.1-9.6-4-9.6-4s-117.2 6.6-177.9 8c-13.3.3-26.5.6-39.6.7v117.2c-5.5-2.6-11.1-5.3-16.6-7.9 0-36.4-.1-109.2-.1-109.2-29 .4-89.2-2.2-89.2-2.2s-141.4-7.1-156.8-8.5c-9.8-.6-22.5-2.1-39 1.5-8.7 1.8-33.5 7.4-53.8 26.9C-4.9 212.4 6.6 276.2 8 285.8c1.7 11.7 6.9 44.2 31.7 72.5 45.8 56.1 144.4 54.8 144.4 54.8s12.1 28.9 30.6 55.5c25 33.1 50.7 58.9 75.7 62 63 0 188.9-.1 188.9-.1s12 .1 28.3-10.3c14-8.5 26.5-23.4 26.5-23.4S547 483 565 451.5c5.5-9.7 10.1-19.1 14.1-28 0 0 55.2-117.1 55.2-231.1-1.1-34.5-9.6-40.6-11.6-42.6M125.6 353.9c-25.9-8.5-36.9-18.7-36.9-18.7S69.6 321.8 60 295.4c-16.5-44.2-1.4-71.2-1.4-71.2s8.4-22.5 38.5-30c13.8-3.7 31-3.1 31-3.1s7.1 59.4 15.7 94.2c7.2 29.2 24.8 77.7 24.8 77.7s-26.1-3.1-43-9.1m300.3 107.6s-6.1 14.5-19.6 15.4c-5.8.4-10.3-1.2-10.3-1.2s-.3-.1-5.3-2.1l-112.9-55s-10.9-5.7-12.8-15.6c-2.2-8.1 2.7-18.1 2.7-18.1L322 273s4.8-9.7 12.2-13c.6-.3 2.3-1 4.5-1.5 8.1-2.1 18 2.8 18 2.8L467.4 315s12.6 5.7 15.3 16.2c1.9 7.4-.5 14-1.8 17.2-6.3 15.4-55 113.1-55 113.1" />
      <path d="M326.8 380.1c-8.2.1-15.4 5.8-17.3 13.8s2 16.3 9.1 20c7.7 4 17.5 1.8 22.7-5.4 5.1-7.1 4.3-16.9-1.8-23.1l24-49.1c1.5.1 3.7.2 6.2-.5 4.1-.9 7.1-3.6 7.1-3.6 4.2 1.8 8.6 3.8 13.2 6.1 4.8 2.4 9.3 4.9 13.4 7.3.9.5 1.8 1.1 2.8 1.9 1.6 1.3 3.4 3.1 4.7 5.5 1.9 5.5-1.9 14.9-1.9 14.9-2.3 7.6-18.4 40.6-18.4 40.6-8.1-.2-15.3 5-17.7 12.5-2.6 8.1 1.1 17.3 8.9 21.3s17.4 1.7 22.5-5.3c5-6.8 4.6-16.3-1.1-22.6 1.9-3.7 3.7-7.4 5.6-11.3 5-10.4 13.5-30.4 13.5-30.4.9-1.7 5.7-10.3 2.7-21.3-2.5-11.4-12.6-16.7-12.6-16.7-12.2-7.9-29.2-15.2-29.2-15.2s0-4.1-1.1-7.1c-1.1-3.1-2.8-5.1-3.9-6.3 4.7-9.7 9.4-19.3 14.1-29-4.1-2-8.1-4-12.2-6.1-4.8 9.8-9.7 19.7-14.5 29.5-6.7-.1-12.9 3.5-16.1 9.4-3.4 6.3-2.7 14.1 1.9 19.8z" />
    </g>
  </svg>
);

const GithubIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg width={32} height={32} viewBox="0 0 16 16" {...props}>
    <path
      fillRule="evenodd"
      d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27s1.36.09 2 .27c1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0 0 16 8c0-4.42-3.58-8-8-8"
    />
  </svg>
);

const GitlabIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg width={26} height={26} {...props}>
    <g fill="none">
      <path
        fill="#FC6D26"
        d="M22.616 14.971 21.52 11.5l-2.173-6.882a.37.37 0 0 0-.71 0L16.465 11.5H9.252L7.079 4.617a.37.37 0 0 0-.71 0l-2.172 6.882L3.1 14.971c-.1.317.01.664.27.86l9.487 7.094 9.487-7.094a.78.78 0 0 0 .27-.86"
      />
      <path fill="#E24329" d="M12.858 22.925 16.465 11.5H9.251z" />
      <path fill="#FC6D26" d="M12.858 22.925 9.251 11.5H4.197z" />
      <path fill="#FCA326" d="M4.197 11.499 3.1 14.971c-.1.317.01.664.27.86l9.487 7.094z" />
      <path fill="#E24329" d="M4.197 11.499H9.25L7.08 4.617a.37.37 0 0 0-.71 0l-2.172 6.882z" />
      <path fill="#FC6D26" d="M12.858 22.925 16.465 11.5h5.055z" />
      <path fill="#FCA326" d="m21.52 11.499 1.096 3.472c.1.317-.01.664-.271.86l-9.487 7.094z" />
      <path fill="#E24329" d="M21.52 11.499h-5.055l2.172-6.882a.37.37 0 0 1 .71 0z" />
    </g>
  </svg>
);

const GridIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" {...props}>
    <path d="M5 3h3a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2m11 0h3a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2h-3a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2m0 11h3a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2h-3a2 2 0 0 1-2-2v-3a2 2 0 0 1 2-2M5 14h3a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-3a2 2 0 0 1 2-2" />
  </svg>
);

const HOptionsIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg width={22} height={20} viewBox="0 0 22 20" {...props}>
    <path fill="#7A8291" d="M3 4h10v12H3zm2 0v5h6V4zm0 7v5h6v-5zm12.874 5.91-3.493-4.117h6.986z" />
  </svg>
);

const H1Icon = (props: SVGProps<SVGSVGElement>) => (
  <svg width={22} height={20} viewBox="0 0 22 20" {...props}>
    <path
      fill="#7A8291"
      d="M3 4h10v12H3zm2 0v5h6V4zm0 7v5h6v-5zm12.068 5v-5.695h-.026l-1.612.767-.325-1.482 2.236-1.04h1.638V16z"
    />
  </svg>
);

const H2Icon = (props: SVGProps<SVGSVGElement>) => (
  <svg width={22} height={20} viewBox="0 0 22 20" {...props}>
    <path
      fill="#7A8291"
      fillRule="evenodd"
      d="M18.036 16h-5.532v-1.104l1.008-.912c1.704-1.524 2.532-2.4 2.556-3.312 0-.636-.384-1.14-1.284-1.14-.672 0-1.26.336-1.668.648L12.6 8.872c.588-.444 1.5-.804 2.556-.804 1.764 0 2.736 1.032 2.736 2.448 0 1.308-.948 2.352-2.076 3.36l-.72.6v.024h2.94zM3 8h7v8H3zm2 0v3h3V8zm0 5v3h3v-3z"
    />
  </svg>
);

const HomeIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg viewBox="0 0 24 24" {...props}>
    <path d="M21 13h-2a1 1 0 0 0-1 1v6h-4v-5a1 1 0 0 0-1-1h-2a1 1 0 0 0-1 1v5H6v-6a1 1 0 0 0-1-1H3l9-9z" />
  </svg>
);

const ImageIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg width={22} height={20} viewBox="0 0 22 20" {...props}>
    <path
      fill="#7A8291"
      d="M5 3h12a3 3 0 0 1 3 3v8a3 3 0 0 1-3 3H5a3 3 0 0 1-3-3V6a3 3 0 0 1 3-3m2.487 7.205-2.34 3.232a1 1 0 0 0 .81 1.586h9.954a1 1 0 0 0 .792-1.611L13.297 9l-3.451 4.469zM8.5 8a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3"
    />
  </svg>
);

const InfoCircleIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg
    width={16}
    height={16}
    fill="currentColor"
    className="bi bi-info-circle"
    viewBox="0 0 16 16"
    {...props}
  >
    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16" />
    <path d="m8.93 6.588-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0" />
  </svg>
);

const ItalicIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg width={22} height={20} viewBox="0 0 22 20" {...props}>
    <path fill="#7A8291" d="M8 4.012V6h2.312l-2.925 8H5v1.988h7V14H9.953l2.925-8H15V4.012z" />
  </svg>
);

const LinkIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg width={22} height={20} viewBox="0 0 22 20" {...props}>
    <path
      fill="#7A8291"
      d="m14.683 10.315-1.256-1.253 1.253-1.254a1.767 1.767 0 0 0 0-2.503 1.765 1.765 0 0 0-2.503 0L9.67 7.81a1.766 1.766 0 0 0 0 2.504l-1.25 1.247-.625-.626a2.657 2.657 0 0 1-.002-3.756l3.135-3.136a3.543 3.543 0 0 1 5.007.009 3.544 3.544 0 0 1 .003 5.007zm-9.394-.626v-.003l1.252 1.249L5.29 12.19a1.767 1.767 0 0 0 0 2.505c.697.695 1.813.69 2.504 0l2.506-2.506a1.766 1.766 0 0 0 0-2.504l1.249-1.249.622.625a2.654 2.654 0 0 1 .006 3.756L9.04 15.953a3.54 3.54 0 0 1-5.004-.002 3.544 3.544 0 0 1-.003-5.008z"
    />
  </svg>
);

const ListBulletedIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg width={22} height={20} viewBox="0 0 22 20" {...props}>
    <path
      fill="#7A8291"
      d="M5 6.5a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3m0 5a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3m0 5a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3M9 4h10v1.964H9zm0 5h10v2H9zm0 5h10v2H9z"
    />
  </svg>
);

const ListNumberedIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg width={22} height={20} viewBox="0 0 22 20" {...props}>
    <path
      fill="#7A8291"
      d="M20.014 4.023v2h-11v-2zm0 5v2h-11v-2zm0 5v2h-11v-2zM3.604 8.985V4.23h-.018l-1.095.545-.22-1.053 1.518-.738h1.113v6zm2.458 7.997h-4v-.835l.73-.69c1.231-1.152 1.83-1.814 1.847-2.503 0-.481-.277-.862-.928-.862-.486 0-.911.254-1.206.49l-.373-.99c.425-.335 1.084-.607 1.848-.607 1.275 0 1.978.78 1.978 1.85 0 .99-.685 1.779-1.5 2.54l-.522.455v.018h2.126z"
    />
  </svg>
);

const ListIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" {...props}>
    <path d="M4.5 3h15a1.5 1.5 0 0 1 0 3h-15a1.5 1.5 0 0 1 0-3m0 5h15a1.5 1.5 0 0 1 0 3h-15a1.5 1.5 0 0 1 0-3m0 5h15a1.5 1.5 0 0 1 0 3h-15a1.5 1.5 0 0 1 0-3m0 5h15a1.5 1.5 0 0 1 0 3h-15a1.5 1.5 0 0 1 0-3" />
  </svg>
);

const MarkdownIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg viewBox="0 0 24 24" {...props}>
    <path d="M1 17V8h2.75l2.75 3.309L9.25 8H12v9H9.25v-5.162l-2.75 3.31-2.75-3.31V17zm18 0-4-4.368h2.667V8h2.666v4.632H23z" />
  </svg>
);

const MediaAltIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" {...props}>
    <path d="M5.027 4.045h13.975a3 3 0 0 1 3 3v9.99a3 3 0 0 1-3 3H5.027a3 3 0 0 1-3-3v-9.99a3 3 0 0 1 3-3m2.874 8.48-4.114 5.504h16.455l-5.485-6.88-4.073 5.105zM9.493 10a1.507 1.507 0 1 0 0-3.014 1.507 1.507 0 0 0 0 3.014" />
  </svg>
);

const MediaIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" {...props}>
    <path d="M21 15.25V4.75C21 3.788 20.212 3 19.25 3H8.75C7.787 3 7 3.788 7 4.75v10.5c0 .962.787 1.75 1.75 1.75h10.5c.962 0 1.75-.788 1.75-1.75m-9.641-3.773 1.787 2.394 2.615-3.277 3.522 4.417H8.717zM3 7v12.25c0 .962.788 1.75 1.75 1.75H17v-1.956H5.98a1 1 0 0 1-1-1V7z" />
  </svg>
);

const NetlifyIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg viewBox="0 0 295 284" {...props}>
    <path fill="#3FB5A0" d="m149.5.372 141.421 141.42L149.5 283.215 8.079 141.793z" />
    <g stroke="#FFF" strokeWidth={8}>
      <path d="M247.788 191.997 1.715 142.5zM293.043 146.743 83.739 60.476zM170.006 269.78 46.97 97.244zM63.94 204.725 179.906 25.12zM175.663 264.122l36.77-206.475zM246.374 91.588 42.02 182.805z" />
    </g>
    <g fill="#FFF" transform="rotate(45 19.795 213.225)">
      <circle cx={14} cy={38} r={14} className="no-fill" />
      <circle cx={77} cy={12} r={12} className="no-fill" />
      <circle cx={116} cy={70} r={12} className="no-fill" />
      <circle cx={35} cy={125} r={16} className="no-fill" />
    </g>
  </svg>
);

const NewTabIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg width={21} height={21} viewBox="0 0 21 21" {...props}>
    <g fillRule="evenodd">
      <path d="M4.7 20.5H15c2.1 0 3.8-1.7 3.8-3.8v-6.4c0-.5-.4-.9-.8-.9-.5 0-1 .4-1 .9v6.4a2 2 0 0 1-2 2H4.7a2 2 0 0 1-2-2V6.2c0-1.1.8-2 2-2H11c.5 0 .8-.4.8-1 0-.4-.3-.8-.8-.8H4.7C2.6 2.4.9 4.1.9 6.2v10.5c0 2 1.7 3.8 3.8 3.8" />
      <path d="M20.9 7.2V1.7h-.1v-.2l-.1-.1-.2-.2h-.1l-.2-.2h-5.7c-.5 0-.8.3-.8.8s.3 1 .8 1H18l-8 8c-.4.3-.4.8 0 1.2.3.3.9.3 1.2 0l8-8v3.2c0 .5.4.9.9.9s.8-.4.9-1z" />
    </g>
  </svg>
);

const PageIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" {...props}>
    <path d="m13.366 3 5.625 5.493L19 19.169C19 20.176 18.156 21 17.125 21H5.865C4.836 21 4 20.176 4 19.17V4.83C4 3.825 4.834 3 5.866 3zM6.94 12.11a.94.94 0 1 0 0 1.88h9.12a.94.94 0 0 0 0-1.88zm0 3.89a.94.94 0 1 0 0 1.88h9.12a.94.94 0 1 0 0-1.88zm5.073-6h5.139l-5.14-5.053z" />
  </svg>
);

const PagesAltIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" {...props}>
    <path d="M21 15.25c0 .962-.788 1.75-1.75 1.75H8.75C7.787 17 7 16.212 7 15.25V4.75C7 3.788 7.787 3 8.75 3h10.5c.962 0 1.75.788 1.75 1.75zM9 10v2h10v-2zm0-4v2h10V6zM3 7v12.25c0 .962.788 1.75 1.75 1.75H17v-1.956H5.98a1 1 0 0 1-1-1V7z" />
  </svg>
);

const PagesIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" {...props}>
    <path d="M3 8h1.98v11.044a1 1 0 0 0 1 1H17V22H4.75C3.788 22 3 21.212 3 20.25zm6-6h6.074L20 7.041V16a2 2 0 0 1-2 2H9a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2m.94 8.11a.94.94 0 1 0 0 1.88h7.12a.94.94 0 0 0 0-1.88zm0 3.89a.94.94 0 1 0 0 1.88h7.12a.94.94 0 1 0 0-1.88zm4.054-6.124h4.344l-4.344-4.342z" />
  </svg>
);

const QuoteIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg width={22} height={20} viewBox="0 0 22 20" {...props}>
    <path
      fill="#7A8291"
      d="M4.995 14.954h2.986l1.991-3.982V5H4v5.972h2.986zm7.963 0h2.986l1.991-3.982V5h-5.972v5.972h2.986z"
    />
  </svg>
);

const RefreshIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg width={20} height={20} viewBox="0 0 20 20" {...props}>
    <path
      fillRule="evenodd"
      d="M13.3 1A9.8 9.8 0 0 0 1.1 7a9.4 9.4 0 0 0 6.2 12c5 1.5 10.3-1 12.1-5.8.2-.6-.1-1.3-.7-1.5-.7-.2-1.4.1-1.6.7a7.3 7.3 0 0 1-9 4.3 7 7 0 0 1-4.7-8.9 7.3 7.3 0 0 1 12-2.8L13 7.4c-.5.5-.3.8.3.8h5.5c.7 0 1.2-.5 1.2-1.1V1.8c0-.7-.4-.8-.9-.4l-2 2c-1-1-2.3-1.9-3.8-2.4"
    />
  </svg>
);

const ScrollIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg viewBox="0 0 24 24" {...props}>
    <path d="M12.809 8.182a.898.898 0 1 1-1.798 0V4.058L8.576 6.494a.898.898 0 1 1-1.271-1.271l3.97-3.97a.925.925 0 0 1 1.27 0l4.026 4.026a.898.898 0 1 1-1.27 1.27l-2.492-2.49zm.015 11.75 2.435-2.436a.899.899 0 1 1 1.27 1.271l-3.969 3.97a.896.896 0 0 1-1.27 0L7.264 18.71a.898.898 0 1 1 1.27-1.271l2.492 2.491v-4.124a.898.898 0 1 1 1.798 0zm-.902-6.479a1.516 1.516 0 1 1 0-3.032 1.516 1.516 0 0 1 0 3.032" />
  </svg>
);

const SearchIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg viewBox="0 0 24 24" {...props}>
    <path d="M20.526 18.236a1.619 1.619 0 1 1-2.29 2.29l-3.341-3.342c-.237-.237-.666-.296-.964-.137 0 0 .04-.01-.22.108a6.881 6.881 0 1 1 3.44-3.436c-.117.258-.105.214-.105.214a.86.86 0 0 0 .138.962zm-9.677-3.466a3.921 3.921 0 1 0 0-7.842 3.921 3.921 0 0 0 0 7.842" />
  </svg>
);

const SettingsIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" {...props}>
    <path d="M18.887 12.874c.037-.287.065-.575.065-.88s-.028-.594-.065-.881l1.954-1.484a.445.445 0 0 0 .11-.575L19.1 5.944c-.111-.198-.361-.27-.565-.198l-2.306.9c-.482-.36-1-.657-1.565-.882l-.352-2.382a.45.45 0 0 0-.454-.377h-3.704a.45.45 0 0 0-.454.377l-.352 2.382a7.2 7.2 0 0 0-1.565.881l-2.306-.899a.46.46 0 0 0-.565.198L3.06 9.054a.435.435 0 0 0 .111.575l1.954 1.484a7 7 0 0 0-.064.88c0 .297.027.594.064.881l-1.954 1.484a.445.445 0 0 0-.11.575l1.851 3.11c.112.198.362.27.565.198l2.306-.9c.482.36 1 .657 1.565.882l.352 2.382a.45.45 0 0 0 .454.377h3.704a.45.45 0 0 0 .454-.377l.352-2.382a7.2 7.2 0 0 0 1.565-.881l2.306.899c.213.08.454 0 .565-.198l1.852-3.11a.445.445 0 0 0-.111-.575zm-6.878 2.132a3.017 3.017 0 0 1-3.013-3.013 3.017 3.017 0 0 1 3.013-3.014 3.017 3.017 0 0 1 3.014 3.014 3.017 3.017 0 0 1-3.014 3.013" />
  </svg>
);

const StrikethroughIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg width={22} height={20} viewBox="0 0 22 20" {...props}>
    <path
      fill="#7A8291"
      d="M13.97 12.046c.073.537.04 1.11-.13 1.724-.426 1.521-1.414 2.557-2.785 2.919a4.5 4.5 0 0 1-1.144.142c-1.673 0-3.4-.832-4.375-1.8l-.42-.449 1.406-1.31.393.424c.79.783 2.428 1.457 3.65 1.136.715-.189 1.18-.704 1.425-1.575.132-.48.136-.875.024-1.211Zm-.256-7.928-1.31 1.401c-.84-.785-2.554-1.409-3.758-1.077-.687.185-1.133.656-1.366 1.437-.435 1.467.534 2.016 3.022 2.764.568.171 1.07.326 1.472.523h5.786v1.92H2.2v-1.92h4.494C5.609 8.39 4.88 7.216 5.44 5.332c.536-1.806 1.766-2.489 2.702-2.744 1.983-.534 4.35.386 5.572 1.529"
    />
  </svg>
);

const UserIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg width={32} height={32} viewBox="0 0 32 32" {...props}>
    <path
      fill="#1E2532"
      fillRule="nonzero"
      d="M16.5 18c-3.025 0-5.5-2.634-5.5-5.854v-.292C11 8.634 13.475 6 16.5 6S22 8.634 22 11.854v.292C22 15.366 19.525 18 16.5 18M16 29c-3.738 0-7.192-1.689-9.39-4.335-.908-1.064-.798-2.7.302-3.601C7.736 20.409 8.753 20 9.88 20h12.645c.742 0 1.43.191 2.062.491 1.43.737 1.869 2.592.88 3.874C23.24 27.175 19.875 29 16 29"
    />
  </svg>
);

const WorkflowIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" {...props}>
    <path d="M10 4h3a1 1 0 0 1 1 1v9a1 1 0 0 1-1 1h-3a1 1 0 0 1-1-1V5a1 1 0 0 1 1-1m7 0h3a1 1 0 0 1 1 1v10a1 1 0 0 1-1 1h-3a1 1 0 0 1-1-1V5a1 1 0 0 1 1-1M3 4h3a1 1 0 0 1 1 1v14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V5a1 1 0 0 1 1-1" />
  </svg>
);

const WriteIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" {...props}>
    <path d="M2.975 7.004c.002-.477.412-.947.897-.948h9.451l-.816 1.896H3.872c-.485 0-.895-.47-.897-.948m.017 8.97c.001.478.395 1.063.88 1.064H8.57c.01-.58.1-1.425.205-1.996H3.872c-.485.001-.879.524-.88 1.001zm7.921-5.008.762-1.997H3.872c-.486 0-.933.521-.933.999 0 .477.447.998.933.998zM2.95 13.041c0 .477.437.965.922.966H9.18c.096-.258.301-.716.419-.968l.445-.964H3.872c-.485 0-.921.489-.922.966m17.099-5.908.395-.849a2.3 2.3 0 0 0-.176-2.374 2.39 2.39 0 0 0-2.207-.984 2.37 2.37 0 0 0-1.936 1.433l-4.712 10.19a9.6 9.6 0 0 0-.699 5.953.61.61 0 0 0 .35.435c.182.081.392.071.564-.027a9.85 9.85 0 0 0 4.104-4.436l3.628-7.843z" />
  </svg>
);

export interface IconImages {
  'add-with': IconComponent;
  add: IconComponent;
  arrow: IconComponent;
  azure: IconComponent;
  bitbucket: IconComponent;
  bold: IconComponent;
  check: IconComponent;
  'chevron-double': IconComponent;
  chevron: IconComponent;
  circle: IconComponent;
  close: IconComponent;
  'code-block': IconComponent;
  code: IconComponent;
  decap: IconComponent;
  'drag-handle': IconComponent;
  eye: IconComponent;
  folder: IconComponent;
  gitea: IconComponent;
  github: IconComponent;
  gitlab: IconComponent;
  grid: IconComponent;
  'h-options': IconComponent;
  h1: IconComponent;
  h2: IconComponent;
  home: IconComponent;
  image: IconComponent;
  'info-circle': IconComponent;
  italic: IconComponent;
  link: IconComponent;
  'list-bulleted': IconComponent;
  'list-numbered': IconComponent;
  list: IconComponent;
  markdown: IconComponent;
  'media-alt': IconComponent;
  media: IconComponent;
  netlify: IconComponent;
  'new-tab': IconComponent;
  page: IconComponent;
  'pages-alt': IconComponent;
  pages: IconComponent;
  quote: IconComponent;
  refresh: IconComponent;
  scroll: IconComponent;
  search: IconComponent;
  settings: IconComponent;
  strikethrough: IconComponent;
  user: IconComponent;
  workflow: IconComponent;
  write: IconComponent;
}

const images: IconImages = {
  'add-with': AddWithIcon,
  add: AddIcon,
  arrow: ArrowIcon,
  azure: AzureIcon,
  bitbucket: BitbucketIcon,
  bold: BoldIcon,
  check: CheckIcon,
  'chevron-double': ChevronDoubleIcon,
  chevron: ChevronIcon,
  circle: CircleIcon,
  close: CloseIcon,
  'code-block': CodeBlockIcon,
  code: CodeIcon,
  decap: DecapIcon,
  'drag-handle': DragHandleIcon,
  eye: EyeIcon,
  folder: FolderIcon,
  gitea: GiteaIcon,
  github: GithubIcon,
  gitlab: GitlabIcon,
  grid: GridIcon,
  'h-options': HOptionsIcon,
  h1: H1Icon,
  h2: H2Icon,
  home: HomeIcon,
  image: ImageIcon,
  'info-circle': InfoCircleIcon,
  italic: ItalicIcon,
  link: LinkIcon,
  'list-bulleted': ListBulletedIcon,
  'list-numbered': ListNumberedIcon,
  list: ListIcon,
  markdown: MarkdownIcon,
  'media-alt': MediaAltIcon,
  media: MediaIcon,
  netlify: NetlifyIcon,
  'new-tab': NewTabIcon,
  page: PageIcon,
  'pages-alt': PagesAltIcon,
  pages: PagesIcon,
  quote: QuoteIcon,
  refresh: RefreshIcon,
  scroll: ScrollIcon,
  search: SearchIcon,
  settings: SettingsIcon,
  strikethrough: StrikethroughIcon,
  user: UserIcon,
  workflow: WorkflowIcon,
  write: WriteIcon,
};

export default images;
