#!/usr/bin/env node
/**
 * Converts SVG files in src/Icon/images/ to a single icons.generated.tsx file
 * using @svgr/core for proper SVG optimization (SVGO) and JSX conversion.
 *
 * The generated file is gitignored and produced during build only.
 *
 * Usage: node scripts/svg-to-tsx.mjs
 */

import { readFileSync, writeFileSync, readdirSync } from 'fs';
import { join, basename, dirname } from 'path';
import { fileURLToPath } from 'url';
import { transform } from '@svgr/core';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const IMAGES_DIR = join(__dirname, '..', 'src', 'Icon', 'images');

/**
 * Convert a filename like "add-with.svg" to a PascalCase component name like "AddWithIcon"
 */
function fileToComponentName(filename) {
  const name = basename(filename, '.svg');
  const pascal = name
    .split(/[-_]/)
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
  return pascal + 'Icon';
}

// Read all SVG files
const svgFiles = readdirSync(IMAGES_DIR)
  .filter(f => f.endsWith('.svg'))
  .sort();

console.log(`Found ${svgFiles.length} SVG files to convert.`);

// Convert each SVG using SVGR
const components = [];
const entries = [];
const iconNames = [];

for (const svgFile of svgFiles) {
  const svgPath = join(IMAGES_DIR, svgFile);
  const componentName = fileToComponentName(svgFile);
  const name = basename(svgFile, '.svg');

  const svgContent = readFileSync(svgPath, 'utf-8');

  // Use SVGR to convert SVG to a React component string
  const tsxCode = await transform(
    svgContent,
    {
      plugins: ['@svgr/plugin-svgo', '@svgr/plugin-jsx'],
      typescript: true,
      exportType: 'named',
      namedExport: componentName,
      jsxRuntime: 'automatic',
      svgoConfig: {
        plugins: [
          {
            name: 'preset-default',
            params: {
              overrides: {
                // Keep viewBox for proper scaling
                removeViewBox: false,
              },
            },
          },
          // Remove non-standard attributes
          'removeXMLNS',
        ],
      },
      // Pass props through to the SVG element
      svgProps: {},
    },
    { componentName },
  );

  // Extract just the component function (strip imports and export)
  // SVGR outputs: import * as React from "react"; ... const ComponentName = (...) => ...; export { ComponentName };
  // We want just the const declaration
  const componentMatch = tsxCode.match(/const\s+\w+\s*=[\s\S]*?(?=;\s*export)/);
  if (componentMatch) {
    components.push(componentMatch[0] + ';');
  } else {
    // Fallback: include the full output minus imports/exports
    const stripped = tsxCode
      .replace(/^import\s+.*;\s*/gm, '')
      .replace(/^export\s+.*;\s*/gm, '')
      .trim();
    components.push(stripped);
  }

  entries.push(`  '${name}': ${componentName},`);
  iconNames.push(`  '${name}': IconComponent;`);

  console.log(`  ✓ ${svgFile} → ${componentName}`);
}

const generatedContent = `/**
 * AUTO-GENERATED FILE — DO NOT EDIT
 *
 * Generated by scripts/svg-to-tsx.mjs from SVG files in this directory.
 * This file is regenerated during build and should not be committed to git.
 */
import type { FC, SVGProps } from 'react';

export type IconComponent = FC<SVGProps<SVGSVGElement>>;

${components.join('\n\n')}

export interface IconImages {
${iconNames.join('\n')}
}

const images: IconImages = {
${entries.join('\n')}
};

export default images;
`;

const outputPath = join(IMAGES_DIR, 'icons.generated.tsx');
writeFileSync(outputPath, generatedContent);
console.log(`\n  ✓ Generated icons.generated.tsx (${svgFiles.length} icons)`);
console.log('Done!');
