import { fireEvent, render, within } from '@testing-library/react';
import React from 'react';
import { describe, expect, it, vi } from 'vitest';

import ObjectControl from '@/widgets/object/ObjectControl';

import type { ObjectControlHandle } from '@/widgets/object/ObjectControl';

function createMockEditorControl(validateSpy: (name: string, value: unknown) => void) {
  return function MockEditorControl(props: Record<string, any>) {
    React.useEffect(() => {
      props.controlRef({
        props: { field: props.field },
        validate: () => validateSpy(props.field.name, props.value),
      });
      // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);
    return <div data-testid={`editor-control-${props.field.name}`} />;
  };
}

describe('ObjectControl', () => {
  const baseProps = {
    onChangeObject: vi.fn(),
    onValidateObject: vi.fn(),
    clearFieldErrors: vi.fn(),
    resolveWidget: vi.fn(),
    classNameWrapper: 'classNameWrapper',
    forID: 'forID',
    t: (key: string) => key,
  };

  it('renders and validates all sub-fields when configured with `fields`', () => {
    const validateSpy = vi.fn();
    const field = {
      name: 'author',
      widget: 'object',
      fields: [
        { name: 'first_name', widget: 'string' },
        { name: 'last_name', widget: 'string' },
      ],
    };

    let handle: ObjectControlHandle | null = null;
    const { getByTestId } = render(
      <ObjectControl
        {...(baseProps as any)}
        field={field}
        value={{ first_name: 'hello', last_name: 'world' }}
        editorControl={createMockEditorControl(validateSpy)}
        ref={h => (handle = h)}
      />,
    );

    expect(getByTestId('editor-control-first_name')).toBeInTheDocument();
    expect(getByTestId('editor-control-last_name')).toBeInTheDocument();

    handle!.validate();
    expect(validateSpy).toHaveBeenCalledWith('first_name', 'hello');
    expect(validateSpy).toHaveBeenCalledWith('last_name', 'world');
  });

  it('renders and validates the sub-field when configured with a singular `field` (single-field list item)', () => {
    const validateSpy = vi.fn();
    const field = {
      name: 'tags',
      widget: 'list',
      field: { name: 'tag', widget: 'string' },
    };

    let handle: ObjectControlHandle | null = null;
    const { getByTestId } = render(
      <ObjectControl
        {...(baseProps as any)}
        field={field}
        forList
        value="a scalar item"
        editorControl={createMockEditorControl(validateSpy)}
        ref={h => (handle = h)}
      />,
    );

    expect(getByTestId('editor-control-tag')).toBeInTheDocument();

    expect(() => handle!.validate()).not.toThrow();
    expect(validateSpy).toHaveBeenCalledWith('tag', 'a scalar item');
  });

  it('resolves a standalone object widget identically whether configured with singular `field` or an equivalent one-element `fields` array', () => {
    // Pins DCMS-805: BREAKING_CHANGES_V2_BETA.md previously claimed singular
    // `field` was removed in favor of `fields`, but ObjectControl still fully
    // supports both, with no deprecation warning. This test asserts the two
    // forms produce identical rendering and validation behavior.
    const singularValidateSpy = vi.fn();
    const pluralValidateSpy = vi.fn();

    const singularField = {
      name: 'author',
      widget: 'object',
      field: { name: 'first_name', widget: 'string' },
    };
    const pluralField = {
      name: 'author',
      widget: 'object',
      fields: [{ name: 'first_name', widget: 'string' }],
    };

    let singularHandle: ObjectControlHandle | null = null;
    const singularResult = render(
      <ObjectControl
        {...(baseProps as any)}
        field={singularField}
        value={{ first_name: 'hello' }}
        editorControl={createMockEditorControl(singularValidateSpy)}
        ref={h => (singularHandle = h)}
      />,
    );

    let pluralHandle: ObjectControlHandle | null = null;
    const pluralResult = render(
      <ObjectControl
        {...(baseProps as any)}
        field={pluralField}
        value={{ first_name: 'hello' }}
        editorControl={createMockEditorControl(pluralValidateSpy)}
        ref={h => (pluralHandle = h)}
      />,
    );

    expect(
      within(singularResult.container).getByTestId('editor-control-first_name'),
    ).toBeInTheDocument();
    expect(
      within(pluralResult.container).getByTestId('editor-control-first_name'),
    ).toBeInTheDocument();
    // Normalize the autogenerated base-ui ids/aria-controls (unique per render
    // instance) before comparing markup, since they differ regardless of the
    // `field` vs `fields` config and aren't part of the behavior being pinned.
    const normalize = (html: string) => html.replace(/base-ui-_r_\d+_/g, 'base-ui-_r_N_');
    expect(normalize(singularResult.container.innerHTML)).toEqual(
      normalize(pluralResult.container.innerHTML),
    );

    singularHandle!.validate();
    pluralHandle!.validate();
    expect(singularValidateSpy).toHaveBeenCalledWith('first_name', 'hello');
    expect(pluralValidateSpy).toHaveBeenCalledWith('first_name', 'hello');
  });

  it('keeps aria-controls on the top-bar expand button pointed at an existing panel id in both open and closed states (DCMS-1725)', () => {
    const field = {
      name: 'author',
      widget: 'object',
      collapsed: false,
      fields: [{ name: 'first_name', widget: 'string' }],
    };

    const { container, getByTestId } = render(
      <ObjectControl
        {...(baseProps as any)}
        field={field}
        value={{ first_name: 'hello' }}
        editorControl={createMockEditorControl(vi.fn())}
      />,
    );

    const expandButton = getByTestId('expand-button');

    // Open state: Base UI already wires this up correctly on its own.
    expect(expandButton).toHaveAttribute('aria-expanded', 'true');
    const openPanelId = expandButton.getAttribute('aria-controls');
    expect(openPanelId).toBeTruthy();
    expect(container.querySelector(`#${CSS.escape(openPanelId!)}`)).not.toBeNull();

    fireEvent.click(expandButton);

    // Closed state: upstream Base UI drops aria-controls here unless we
    // backfill it (the DCMS-1725 bug); it must still reference a real node.
    expect(expandButton).toHaveAttribute('aria-expanded', 'false');
    const closedPanelId = expandButton.getAttribute('aria-controls');
    expect(closedPanelId).toBeTruthy();
    expect(closedPanelId).toBe(openPanelId);
    expect(container.querySelector(`#${CSS.escape(closedPanelId!)}`)).not.toBeNull();
  });

  it('renders a message when neither `field` nor `fields` is defined', () => {
    const validateSpy = vi.fn();
    const field = { name: 'broken', widget: 'object' };

    let handle: ObjectControlHandle | null = null;
    const { getByText } = render(
      <ObjectControl
        {...(baseProps as any)}
        field={field}
        editorControl={createMockEditorControl(validateSpy)}
        ref={h => (handle = h)}
      />,
    );

    expect(getByText('No field(s) defined for this widget')).toBeInTheDocument();
    expect(() => handle!.validate()).not.toThrow();
  });
});
