import AuthenticationPage, { renderPageLogo, StandaloneAuthPage } from './AuthenticationPage';
import Dropdown, {
  DropdownButton,
  DropdownCheckedItem,
  DropdownItem,
  DropdownRadioItem,
  StyledDropdownButton,
} from './Dropdown';
import FieldLabel from './FieldLabel';
import GoBackButton from './GoBackButton';
import Icon from './Icon';
import IconButton from './IconButton';
import ListItemTopBar from './ListItemTopBar';
import Loader from './Loader';
import ObjectWidgetTopBar, { type TranslateFunction } from './ObjectWidgetTopBar';
import PatLoginForm from './PatLoginForm';
import { SortableArea, SortableHandle, SortableItem } from './Sortable';
import {
  borders,
  buttons,
  colors,
  colorsDefaults,
  colorsRaw,
  colorsRawDefaults,
  components,
  DefaultTokensGlobalStyle,
  effects,
  fonts,
  GlobalStyles,
  lengths,
  shadows,
  text,
  themeToCssVars,
  transitions,
  zIndex,
} from './styles';
import Toggle, { ToggleBackground, ToggleContainer, ToggleHandle } from './Toggle';
import WidgetPreviewContainer from './WidgetPreviewContainer';

export type { SortableItemState, SortEndArgs } from './Sortable';
export type { DecapTheme } from './styles';

export const DecapCmsUiDefault = {
  Dropdown,
  DropdownItem,
  DropdownCheckedItem,
  DropdownRadioItem,
  DropdownButton,
  StyledDropdownButton,
  ListItemTopBar,
  FieldLabel,
  Icon,
  IconButton,
  Loader,
  Toggle,
  ToggleContainer,
  ToggleBackground,
  ToggleHandle,
  AuthenticationPage,
  PatLoginForm,
  WidgetPreviewContainer,
  ObjectWidgetTopBar,
  fonts,
  colorsRaw,
  colors,
  colorsDefaults,
  colorsRawDefaults,
  lengths,
  components,
  buttons,
  shadows,
  text,
  borders,
  transitions,
  effects,
  zIndex,
  GlobalStyles,
  DefaultTokensGlobalStyle,
  themeToCssVars,
  renderPageLogo,
};
export {
  AuthenticationPage,
  borders,
  buttons,
  colors,
  colorsDefaults,
  colorsRaw,
  colorsRawDefaults,
  components,
  DefaultTokensGlobalStyle,
  Dropdown,
  DropdownButton,
  DropdownCheckedItem,
  DropdownItem,
  DropdownRadioItem,
  effects,
  FieldLabel,
  fonts,
  GlobalStyles,
  GoBackButton,
  Icon,
  IconButton,
  lengths,
  ListItemTopBar,
  Loader,
  ObjectWidgetTopBar,
  PatLoginForm,
  renderPageLogo,
  shadows,
  SortableArea,
  SortableHandle,
  SortableItem,
  StandaloneAuthPage,
  StyledDropdownButton,
  text,
  themeToCssVars,
  Toggle,
  ToggleBackground,
  ToggleContainer,
  ToggleHandle,
  transitions,
  TranslateFunction,
  WidgetPreviewContainer,
  zIndex,
};
