/**
 * `possibleTypes` map for the GitHub GraphQL schema, consumed by
 * `InMemoryCache` so fragments on interfaces and unions match correctly.
 * Derived from the schema introspection result (supertype -> implementing
 * object types).
 */
export default {
  Node: [
    'AddedToProjectEvent',
    'App',
    'AssignedEvent',
    'BaseRefChangedEvent',
    'BaseRefForcePushedEvent',
    'Blob',
    'Bot',
    'BranchProtectionRule',
    'ClosedEvent',
    'CodeOfConduct',
    'CommentDeletedEvent',
    'Commit',
    'CommitComment',
    'CommitCommentThread',
    'ConvertedNoteToIssueEvent',
    'CrossReferencedEvent',
    'DemilestonedEvent',
    'DeployKey',
    'DeployedEvent',
    'Deployment',
    'DeploymentEnvironmentChangedEvent',
    'DeploymentStatus',
    'ExternalIdentity',
    'Gist',
    'GistComment',
    'HeadRefDeletedEvent',
    'HeadRefForcePushedEvent',
    'HeadRefRestoredEvent',
    'Issue',
    'IssueComment',
    'Label',
    'LabeledEvent',
    'Language',
    'License',
    'LockedEvent',
    'Mannequin',
    'MarketplaceCategory',
    'MarketplaceListing',
    'MentionedEvent',
    'MergedEvent',
    'Milestone',
    'MilestonedEvent',
    'MovedColumnsInProjectEvent',
    'Organization',
    'OrganizationIdentityProvider',
    'OrganizationInvitation',
    'PinnedEvent',
    'Project',
    'ProjectCard',
    'ProjectColumn',
    'PublicKey',
    'PullRequest',
    'PullRequestCommit',
    'PullRequestCommitCommentThread',
    'PullRequestReview',
    'PullRequestReviewComment',
    'PullRequestReviewThread',
    'PushAllowance',
    'Reaction',
    'ReadyForReviewEvent',
    'Ref',
    'ReferencedEvent',
    'RegistryPackage',
    'RegistryPackageDependency',
    'RegistryPackageFile',
    'RegistryPackageTag',
    'RegistryPackageVersion',
    'Release',
    'ReleaseAsset',
    'RemovedFromProjectEvent',
    'RenamedTitleEvent',
    'ReopenedEvent',
    'Repository',
    'RepositoryInvitation',
    'RepositoryTopic',
    'ReviewDismissalAllowance',
    'ReviewDismissedEvent',
    'ReviewRequest',
    'ReviewRequestRemovedEvent',
    'ReviewRequestedEvent',
    'SavedReply',
    'SecurityAdvisory',
    'SponsorsListing',
    'Sponsorship',
    'Status',
    'StatusContext',
    'SubscribedEvent',
    'Tag',
    'Team',
    'Topic',
    'TransferredEvent',
    'Tree',
    'UnassignedEvent',
    'UnlabeledEvent',
    'UnlockedEvent',
    'UnpinnedEvent',
    'UnsubscribedEvent',
    'User',
    'UserBlockedEvent',
    'UserContentEdit',
    'UserStatus',
  ],
  UniformResourceLocatable: [
    'Bot',
    'ClosedEvent',
    'Commit',
    'CrossReferencedEvent',
    'Gist',
    'Issue',
    'Mannequin',
    'MergedEvent',
    'Milestone',
    'Organization',
    'PullRequest',
    'PullRequestCommit',
    'ReadyForReviewEvent',
    'Release',
    'Repository',
    'RepositoryTopic',
    'ReviewDismissedEvent',
    'User',
  ],
  Actor: ['Bot', 'Mannequin', 'Organization', 'User'],
  RegistryPackageOwner: ['Organization', 'Repository', 'User'],
  ProjectOwner: ['Organization', 'Repository', 'User'],
  Closable: ['Issue', 'Milestone', 'Project', 'PullRequest'],
  Updatable: [
    'CommitComment',
    'GistComment',
    'Issue',
    'IssueComment',
    'Project',
    'PullRequest',
    'PullRequestReview',
    'PullRequestReviewComment',
  ],
  ProjectCardItem: ['Issue', 'PullRequest'],
  Assignable: ['Issue', 'PullRequest'],
  Comment: [
    'CommitComment',
    'GistComment',
    'Issue',
    'IssueComment',
    'PullRequest',
    'PullRequestReview',
    'PullRequestReviewComment',
  ],
  UpdatableComment: [
    'CommitComment',
    'GistComment',
    'Issue',
    'IssueComment',
    'PullRequest',
    'PullRequestReview',
    'PullRequestReviewComment',
  ],
  Labelable: ['Issue', 'PullRequest'],
  Lockable: ['Issue', 'PullRequest'],
  RegistryPackageSearch: ['Organization', 'User'],
  RepositoryOwner: ['Organization', 'User'],
  MemberStatusable: ['Organization', 'Team'],
  ProfileOwner: ['Organization', 'User'],
  PinnableItem: ['Gist', 'Repository'],
  Starrable: ['Gist', 'Repository', 'Topic'],
  RepositoryInfo: ['Repository'],
  GitObject: ['Blob', 'Commit', 'Tag', 'Tree'],
  RepositoryNode: [
    'CommitComment',
    'CommitCommentThread',
    'Issue',
    'IssueComment',
    'PullRequest',
    'PullRequestCommitCommentThread',
    'PullRequestReview',
    'PullRequestReviewComment',
  ],
  Subscribable: ['Commit', 'Issue', 'PullRequest', 'Repository', 'Team'],
  Deletable: ['CommitComment', 'GistComment', 'IssueComment', 'PullRequestReview', 'PullRequestReviewComment'],
  Reactable: ['CommitComment', 'Issue', 'IssueComment', 'PullRequest', 'PullRequestReview', 'PullRequestReviewComment'],
  GitSignature: ['GpgSignature', 'SmimeSignature', 'UnknownSignature'],
  RequestedReviewer: ['User', 'Team', 'Mannequin'],
  PullRequestTimelineItem: [
    'Commit',
    'CommitCommentThread',
    'PullRequestReview',
    'PullRequestReviewThread',
    'PullRequestReviewComment',
    'IssueComment',
    'ClosedEvent',
    'ReopenedEvent',
    'SubscribedEvent',
    'UnsubscribedEvent',
    'MergedEvent',
    'ReferencedEvent',
    'CrossReferencedEvent',
    'AssignedEvent',
    'UnassignedEvent',
    'LabeledEvent',
    'UnlabeledEvent',
    'MilestonedEvent',
    'DemilestonedEvent',
    'RenamedTitleEvent',
    'LockedEvent',
    'UnlockedEvent',
    'DeployedEvent',
    'DeploymentEnvironmentChangedEvent',
    'HeadRefDeletedEvent',
    'HeadRefRestoredEvent',
    'HeadRefForcePushedEvent',
    'BaseRefForcePushedEvent',
    'ReviewRequestedEvent',
    'ReviewRequestRemovedEvent',
    'ReviewDismissedEvent',
    'UserBlockedEvent',
  ],
  Closer: ['Commit', 'PullRequest'],
  ReferencedSubject: ['Issue', 'PullRequest'],
  Assignee: ['Bot', 'Mannequin', 'Organization', 'User'],
  MilestoneItem: ['Issue', 'PullRequest'],
  RenamedTitleSubject: ['Issue', 'PullRequest'],
  PullRequestTimelineItems: [
    'PullRequestCommit',
    'PullRequestCommitCommentThread',
    'PullRequestReview',
    'PullRequestReviewThread',
    'PullRequestRevisionMarker',
    'BaseRefChangedEvent',
    'BaseRefForcePushedEvent',
    'DeployedEvent',
    'DeploymentEnvironmentChangedEvent',
    'HeadRefDeletedEvent',
    'HeadRefForcePushedEvent',
    'HeadRefRestoredEvent',
    'MergedEvent',
    'ReviewDismissedEvent',
    'ReviewRequestedEvent',
    'ReviewRequestRemovedEvent',
    'ReadyForReviewEvent',
    'IssueComment',
    'CrossReferencedEvent',
    'AddedToProjectEvent',
    'AssignedEvent',
    'ClosedEvent',
    'CommentDeletedEvent',
    'ConvertedNoteToIssueEvent',
    'DemilestonedEvent',
    'LabeledEvent',
    'LockedEvent',
    'MentionedEvent',
    'MilestonedEvent',
    'MovedColumnsInProjectEvent',
    'PinnedEvent',
    'ReferencedEvent',
    'RemovedFromProjectEvent',
    'RenamedTitleEvent',
    'ReopenedEvent',
    'SubscribedEvent',
    'TransferredEvent',
    'UnassignedEvent',
    'UnlabeledEvent',
    'UnlockedEvent',
    'UserBlockedEvent',
    'UnpinnedEvent',
    'UnsubscribedEvent',
  ],
  IssueOrPullRequest: ['Issue', 'PullRequest'],
  IssueTimelineItem: [
    'Commit',
    'IssueComment',
    'CrossReferencedEvent',
    'ClosedEvent',
    'ReopenedEvent',
    'SubscribedEvent',
    'UnsubscribedEvent',
    'ReferencedEvent',
    'AssignedEvent',
    'UnassignedEvent',
    'LabeledEvent',
    'UnlabeledEvent',
    'UserBlockedEvent',
    'MilestonedEvent',
    'DemilestonedEvent',
    'RenamedTitleEvent',
    'LockedEvent',
    'UnlockedEvent',
    'TransferredEvent',
  ],
  IssueTimelineItems: [
    'IssueComment',
    'CrossReferencedEvent',
    'AddedToProjectEvent',
    'AssignedEvent',
    'ClosedEvent',
    'CommentDeletedEvent',
    'ConvertedNoteToIssueEvent',
    'DemilestonedEvent',
    'LabeledEvent',
    'LockedEvent',
    'MentionedEvent',
    'MilestonedEvent',
    'MovedColumnsInProjectEvent',
    'PinnedEvent',
    'ReferencedEvent',
    'RemovedFromProjectEvent',
    'RenamedTitleEvent',
    'ReopenedEvent',
    'SubscribedEvent',
    'TransferredEvent',
    'UnassignedEvent',
    'UnlabeledEvent',
    'UnlockedEvent',
    'UserBlockedEvent',
    'UnpinnedEvent',
    'UnsubscribedEvent',
  ],
  ReviewDismissalAllowanceActor: ['User', 'Team'],
  PushAllowanceActor: ['User', 'Team'],
  PermissionGranter: ['Organization', 'Repository', 'Team'],
  Sponsorable: ['User'],
  Contribution: [
    'CreatedCommitContribution',
    'CreatedIssueContribution',
    'CreatedPullRequestContribution',
    'CreatedPullRequestReviewContribution',
    'CreatedRepositoryContribution',
    'JoinedGitHubContribution',
    'RestrictedContribution',
  ],
  CreatedRepositoryOrRestrictedContribution: ['CreatedRepositoryContribution', 'RestrictedContribution'],
  CreatedIssueOrRestrictedContribution: ['CreatedIssueContribution', 'RestrictedContribution'],
  CreatedPullRequestOrRestrictedContribution: ['CreatedPullRequestContribution', 'RestrictedContribution'],
  SearchResultItem: ['Issue', 'PullRequest', 'Repository', 'User', 'Organization', 'MarketplaceListing', 'App'],
  CollectionItemContent: ['Repository', 'Organization', 'User'],
};
