import { concat, isEmpty, last, nth } from 'lodash-es';
import visitParents from 'unist-util-visit-parents';

import type { MdastNode } from '@/widgets/richtext/types';

/**
 * remarkUnwrapInvalidNest
 *
 * Some MDAST node types can only be nested within specific node types - for
 * example, a paragraph can't be nested within another paragraph, and a heading
 * can't be nested in a "strong" type node. This kind of invalid MDAST can be
 * generated by rehype-remark from invalid HTML.
 *
 * This plugin finds instances of invalid nesting, and unwraps the invalidly
 * nested nodes as far up the parental line as necessary, splitting parent nodes
 * along the way. The resulting node has no invalidly nested nodes, and all
 * validly nested nodes retain their ancestry. Nodes that are emptied as a
 * result of unnesting nodes are removed from the tree.
 */
export default function remarkUnwrapInvalidNest() {
  /**
   * Node types that are considered "blocks".
   */
  const blocks = ['paragraph', 'heading', 'code', 'blockquote', 'list', 'table', 'thematicBreak'];

  /**
   * Node types that can contain "block" nodes as direct children.
   */
  const canContainBlocks = ['root', 'blockquote', 'listItem', 'tableCell'];

  /**
   * visitParents uses unist-util-visit-parent to check every node in the
   * tree while having access to every ancestor of the node. This is ideal
   * for determining whether a block node has an ancestor that should not
   * contain a block node. Note that it operates in a mutable fashion.
   */
  function findInvalidNest(tree: MdastNode): MdastNode[] | undefined {
    let invalidNest: MdastNode[] | undefined;

    visitParents(tree, (node, parents) => {
      const parent = last(parents);
      const parentType = !isEmpty(parents) && parent ? parent.type : false;
      const isInvalidNest = blocks.includes(node.type)
        && (parentType === false || !canContainBlocks.includes(parentType));

      if (isInvalidNest) {
        invalidNest = concat(parents, node);
        return false;
      }
    });

    return invalidNest;
  }

  function splitTreeAtNest(tree: MdastNode, nest: MdastNode[]) {
    const grandparent = nth(nest, -3) ?? tree;
    const parent = nth(nest, -2);
    const node = last(nest);

    if (!parent || !node || !grandparent.children || !parent.children) return;

    const splitChildren = grandparent.children;
    const splitIndex = splitChildren.indexOf(parent);
    const splitChildIndex = parent.children.indexOf(node);

    const childrenBefore = parent.children.slice(0, splitChildIndex);
    const childrenAfter = parent.children.slice(splitChildIndex + 1);
    const nodeBefore = isEmpty(childrenBefore) ? undefined : { ...parent, children: childrenBefore };
    const nodeAfter = isEmpty(childrenAfter) ? undefined : { ...parent, children: childrenAfter };

    const childrenToInsert = [nodeBefore, node, nodeAfter].filter(
      (val): val is MdastNode => val !== undefined && !isEmpty(val),
    );
    const beforeChildren = splitChildren.slice(0, splitIndex);
    const afterChildren = splitChildren.slice(splitIndex + 1);

    grandparent.children = concat(beforeChildren, childrenToInsert, afterChildren);
  }

  function transform(tree: MdastNode): MdastNode {
    const invalidNest = findInvalidNest(tree);

    if (!invalidNest) return tree;

    splitTreeAtNest(tree, invalidNest);

    return transform(tree);
  }

  return transform;
}
