import { describe, expect, it } from 'vitest';

import { fuzzyFilter } from '@/lib/util/core-utils/fuzzy.js';

// Characterization tests: all expected scores and orderings were generated by
// running the original `fuzzy` 0.1.3 package against the same inputs.
describe('fuzzyFilter', () => {
  const identity = (s: string) => s;

  it('matches case-insensitive subsequences and excludes non-matches', () => {
    const results = fuzzyFilter('bcn', ['bacon', 'cabbage', 'BaCoN'], identity);
    expect(results.map(r => r.original)).toEqual(['bacon', 'BaCoN']);
    expect(results.map(r => r.score)).toEqual([3, 3]);
  });

  it('scores an exact match as Infinity so it sorts first', () => {
    const results = fuzzyFilter('bcn', ['bacon', 'bcn'], identity);
    expect(results.map(r => r.original)).toEqual(['bcn', 'bacon']);
    expect(results[0].score).toBe(Infinity);
  });

  it('scores consecutive matching characters superlinearly', () => {
    const results = fuzzyFilter(
      'find me by title',
      ['find me by short title', 'unrelated'],
      identity,
    );
    expect(results).toEqual([{ index: 0, score: 4110, original: 'find me by short title' }]);
  });

  it('keeps input order on score ties, including exact-match ties', () => {
    const tied = fuzzyFilter('me', ['find me', 'me find', 'theme'], identity);
    expect(tied.map(r => r.index)).toEqual([0, 1, 2]);
    expect(tied.map(r => r.score)).toEqual([4, 4, 4]);

    const exactTies = fuzzyFilter('me', ['me', 'ME'], identity);
    expect(exactTies.map(r => r.index)).toEqual([0, 1]);
  });

  it('matches everything with score 0 for an empty pattern', () => {
    expect(fuzzyFilter('', ['a', 'b'], identity)).toEqual([
      { index: 0, score: 0, original: 'a' },
      { index: 1, score: 0, original: 'b' },
    ]);
  });

  it('returns an empty array for an empty input array', () => {
    expect(fuzzyFilter('a', [], identity)).toEqual([]);
  });

  it('extracts the compared string from arbitrary elements and reports their index', () => {
    const files = [{ name: 'posts/find-me.md' }, { name: 'nope' }, { name: 'post.md' }];
    const results = fuzzyFilter('post', files, file => file.name);
    expect(results).toEqual([
      { index: 0, score: 26, original: files[0] },
      { index: 2, score: 26, original: files[2] },
    ]);
  });
});
